### ISSUE TITLE
Is there still circular dependency problem?

### ISSUE THREAD

**Issue by langpavel** [jscomplete/graphql-makers#1]
From your nice article [The API I wish JavaScript GraphQL implementations supported](https://jscomplete.com/learn/19xfr-the-api-I-wish-graphql-implementations-supported):
> Please note that the objectType code above is just the basic use case. There are many other use cases that require further code. For example, if the types have circular dependencies (article → author → article) then this version of objectType will not work. We can delay the loading of the circular dependencies until we’re in the fields thunk (which is the current approach to solve this problem in the object-based method). We can also use the "extend" syntax to design the schema in a way that avoids circular dependencies in the first place. I’ve skipped this part to keep the example simple.

Is this solved in this library?

**Comment by samerbuna** [comment]
It should be but I've only done minimal testings on that.
