### ISSUE TITLE
Why are `dependencies` needed

### ISSUE THREAD

**Issue by langpavel** [jscomplete/graphql-makers#2]
In this sample,
there is `dependencies` map, which maps other type implementation by name,
`Coments` to their implementation elsewhere.

```js
const { objectType } = require('graphql-makers');

const dependencies = {
  Comment: require.resolve('./comment'),
};

const typeDef = `...`;

const resolvers = {
  user(parent, args, contex) { /* ... */ },
  comments(parent, args, context) { /* ... */ },
};

module.exports = objectType({ typeDef, resolvers, dependencies });
```
### Now the question:
Can this be workarounded by `schema.getNamedType()` in implementation?
My first fast though is yes, but really, I'm not sure

**Comment by samerbuna** [comment]
The `comments` field is `[Comment!]!`. The type `Comment` has to come from somewhere.

**Comment by langpavel** [comment]
Hi, my question was probably stupid :-D Shema needs know definitions
